### ISSUE TITLE
engage.executeTransact is not a function

### ISSUE THREAD

**Issue by becauseinterwebs** [Silverpop/node-engage#15]
Just downloaded the lib specifically for this function as described in the methods doc but apparently it doesn't exist in the code?

**Comment by ehutson** [comment]
The functionality was in the code, but hadn't been published to NPM.

As of today, the name of the repository has been changed.
It used to be `engage-api`.  It is now `watson-campaign-automation-api`.

So, if you update your `package.json` to reflect the new name and version, you should have access to the Transact functionality.

Like this:

```
"dependencies": {
        "watson-campaign-automation-api": "^0.1.7"
}
```

Let me know if that doesn't resolve your issue.
