### ISSUE TITLE
RemoveRecipient is not implemented

### ISSUE THREAD

**Issue by creativeux** [Silverpop/node-engage#19]
Has this been deprecated? If so, how can we remove recipients from contact lists if opt-out is a global concept?

I solved this locally by creating a `remove-recipient.js` class in the `xml-api` folder.

**Comment by creativeux** [comment]
I have a branch I can push with a fix, but require permissions.

**Comment by creativeux** [comment]
[Pull request #21 open](https://github.com/Silverpop/node-engage/pull/21)

**Comment by ehutson** [comment]
The pull request has been merged and version 0.1.8 has been published.
Closing issue.
