### ISSUE TITLE
hitting with an issue Failed to get list metadata: Failed to make Engage XML API request: HTTP status 401: Invalid client: Unable to find matc hing client for xxxxxx

### ISSUE THREAD

**Issue by apasrini** [Silverpop/node-engage#4]

**Comment by apasrini** [comment]
hitting with the above issue but the client id seems to be correct and able to invoke it with rest apis.

**Comment by smitchelus** [comment]
Can you show the code you are using to make the call?

**Comment by ehutson** [comment]
This is very old... going to go ahead and close
