### ISSUE TITLE
Accepting international characters

### ISSUE THREAD

**Issue by rtirserio** [Silverpop/node-engage#8]
When you attempt to submit international characters (`ã` for example), you get the following response

```
<Envelope>
  <Body>
    <RESULT>
      <SUCCESS>false</SUCCESS>
    </RESULT>
    <Fault>
      <Request/>
        <FaultCode/>
          <FaultString>Invalid XML Request</FaultString>
          <detail>
            <error>
             <errorid>51</errorid>
             <module/>
             <class>SP.API</class>
             <method/>
           </error>
         </detail>
     </Fault>
  </Body>
</Envelope>
```

**Comment by rtirserio** [comment]
I think this is a bug with the XML API not accepting the international characters unless the request is sent with a Content-Type header of `application/x-www-form-urlencoded`. For this to work, you also need to have the XML assigned to a param named `xml`

**Comment by jalibu** [comment]
The pull requests solves a major bug for many languages such as German, French, etc...
